// Eksport wszystkich komponentów z jednego miejsca
export { default as Navbar } from './Navbar'
export { default as Sidebar } from './Sidebar'
export { default as Hero } from './Hero'
export { default as Card } from './Card'
export { default as ProgressBar } from './ProgressBar'
export { default as ExperienceBar } from './ExperienceBar'
export { default as GameModeCard } from './GameModeCard'
export { default as CategoryCard } from './CategoryCard'
export { default as AchievementBadge } from './AchievementBadge'
export { default as StatsGrid } from './StatsGrid'
export { default as Layout } from './Layout'

// Pages
export { default as Home } from '../pages/Home'
export { default as Ranking } from '../pages/Ranking'
export { default as DailyMissions } from '../pages/DailyMissions'
export { default as GameHistory } from '../pages/GameHistory'
export { default as Shop } from '../pages/Shop'
export { default as Friends } from '../pages/Friends'
export { default as FriendSearch } from '../pages/FriendSearch'
export { default as Chat } from '../pages/Chat'
export { default as TopPlayers } from '../pages/TopPlayers'
export { default as Settings } from '../pages/Settings'
export { default as AddQuestion } from '../pages/AddQuestion'
export { default as AdminPanel } from '../pages/AdminPanel'
